In [1]:
import pandas as pd


In [2]:
df = pd.read_csv('/content/drive/MyDrive/INNOV8-2.0-47055a37a3bccfe6a5b7de82a2e87f9bc71a24bc/INNOV8-2.0-47055a37a3bccfe6a5b7de82a2e87f9bc71a24bc/data.csv')
df_test = pd.read_csv('/content/drive/MyDrive/INNOV8-2.0-47055a37a3bccfe6a5b7de82a2e87f9bc71a24bc/INNOV8-2.0-47055a37a3bccfe6a5b7de82a2e87f9bc71a24bc/test.csv')

In [3]:
df.head()

message  fingers tail  species
0                        pluvia arbor aquos        4   no   Aquari
1                 cosmix xeno nebuz odbitaz        5  yes  Zorblax
2        solarix glixx novum galaxum quasar        5  yes  Zorblax
3  arbor insectus pesros ekos dootix nimbus        2  yes  Florian
4         mermax drakos lorix epikoz deftax        4   no   Faerix

In [4]:
df_test.head()

message  fingers tail
0         iephyr terram nimbus terram faunar foliar        2   no
1        joyzor uleex luvium caloox shockus blissae        4  yes
2                                aquos arbor ventuc        4  yes
3  nympha nympha epikoz nympha mythox mythox mythox        3   no
4                            diitax sibenix fabulon        4  yes

In [5]:
df['tail'] = df['tail'].map({'yes': 1, 'no': 0})
df_test['tail'] = df_test['tail'].map({'yes': 1, 'no': 0})

In [6]:
df.head()

message  fingers  tail  species
0                        pluvia arbor aquos        4     0   Aquari
1                 cosmix xeno nebuz odbitaz        5     1  Zorblax
2        solarix glixx novum galaxum quasar        5     1  Zorblax
3  arbor insectus pesros ekos dootix nimbus        2     1  Florian
4         mermax drakos lorix epikoz deftax        4     0   Faerix

In [7]:
# from sklearn.preprocessing import LabelEncoder


# # Initialize LabelEncoder
# label_encoder = LabelEncoder()

# # Apply LabelEncoder to the 'species' column
# df['species'] = label_encoder.fit_transform(df['species'])

# df.head()


In [7]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

# Initialize CountVectorizer with binary=True for 1/0 encoding
vectorizer = CountVectorizer(binary=True)

# Fit and transform the 'message' column to create the one-hot encoded word matrix
word_matrix = vectorizer.fit_transform(df['message'])

# Convert the matrix to a DataFrame with column names corresponding to the words
word_df = pd.DataFrame(word_matrix.toarray(), columns=vectorizer.get_feature_names_out())

# Concatenate the original DataFrame with the new word columns
df = pd.concat([df, word_df], axis=1)

df.head()

message  fingers  tail  species  acon  \
0                        pluvia arbor aquos        4     0   Aquari     0   
1                 cosmix xeno nebuz odbitaz        5     1  Zorblax     0   
2        solarix glixx novum galaxum quasar        5     1  Zorblax     0   
3  arbor insectus pesros ekos dootix nimbus        2     1  Florian     0   
4         mermax drakos lorix epikoz deftax        4     0   Faerix     0   

   aeon  aeop  aeqn  afgstix  airenix  ...  zenrx  zephyr  zeqox  zgphyr  \
0     0     0     0        0        0  ...      0       0      0       0   
1     0     0     0        0        0  ...      0       0      0       0   
2     0     0     0        0        0  ...      0       0      0       0   
3     0     0     0        0        0  ...      0       0      0       0   
4     0     0     0        0        0  ...      0       0      0       0   

   znikor  zolp  zorf  zorp  zquos  zyrp  
0       0     0     0     0      0     0  
1       0     0     0     0      0     0  
2       0     0     0     0      0     0  
3       0     0     0     0      0     0  
4       0     0     0     0      0     0  

[5 rows x 640 columns]

In [8]:

# Initialize CountVectorizer with binary=True for 1/0 encoding
vectorizer = CountVectorizer(binary=True)

# Fit and transform the 'message' column to create the one-hot encoded word matrix
word_matrixtest = vectorizer.fit_transform(df_test['message'])

# Convert the matrix to a DataFrame with column names corresponding to the words
word_dftest = pd.DataFrame(word_matrixtest.toarray(), columns=vectorizer.get_feature_names_out())

# Concatenate the original DataFrame with the new word columns
df_test = pd.concat([df_test, word_dftest], axis=1)

df_test.head()

message  fingers  tail  aeiana  \
0         iephyr terram nimbus terram faunar foliar        2     0       0   
1        joyzor uleex luvium caloox shockus blissae        4     1       0   
2                                aquos arbor ventuc        4     1       0   
3  nympha nympha epikoz nympha mythox mythox mythox        3     0       0   
4                            diitax sibenix fabulon        4     1       0   

   aeno  aeon  alezom  algocix  algorik  algorix  ...  zenox  zenzx  zephyr  \
0     0     0       0        0        0        0  ...      0      0       0   
1     0     0       0        0        0        0  ...      0      0       0   
2     0     0       0        0        0        0  ...      0      0       0   
3     0     0       0        0        0        0  ...      0      0       0   
4     0     0       0        0        0        0  ...      0      0       0   

   zephyv  zezhyr  zitanos  zoblax  zofp  zorp  zoyp  
0       0       0        0       0     0     0     0  
1       0       0        0       0     0     0     0  
2       0       0        0       0     0     0     0  
3       0       0        0       0     0     0     0  
4       0       0        0       0     0     0     0  

[5 rows x 437 columns]

In [18]:
# Columns in df but not in df_test
cols_in_df_not_in_test = set(df.columns) - set(df_test.columns)
print("Columns in df but not in df_test:", cols_in_df_not_in_test)

# Columns in df_test but not in df
cols_in_test_not_in_df = set(df_test.columns) - set(df.columns)
print("Columns in df_test but not in df:", cols_in_test_not_in_df)


Columns in df but not in df_test: {'species'}
Columns in df_test but not in df: set()


In [10]:
from sklearn.feature_extraction.text import CountVectorizer

# Function to add missing columns and populate them
def add_missing_columns(df, df_test):
    # Identify columns that are in df but not in df_test, excluding 'species'
    cols_in_df_not_in_test = set(df.columns) - set(df_test.columns) - {'species'}
    cols_in_test_not_in_df = set(df_test.columns) - set(df.columns)

    # Add missing columns to df_test
    for col in cols_in_df_not_in_test:
        df_test[col] = 0  # Initialize with 0

    # Add missing columns to df
    for col in cols_in_test_not_in_df:
        if col != 'species':  # Skip 'species' when adding to df
            df[col] = 0  # Initialize with 0

    # Transform 'message' column to create word presence for df
    vectorizer = CountVectorizer(binary=True)
    word_matrix_df = vectorizer.fit_transform(df['message'])
    word_df = pd.DataFrame(word_matrix_df.toarray(), columns=vectorizer.get_feature_names_out())

    # Set the appropriate columns in df based on the presence in 'message'
    for col in word_df.columns:
        if col in df.columns:
            df[col] = word_df[col]

    # Transform 'message' column to create word presence for df_test
    word_matrix_test = vectorizer.transform(df_test['message'])
    word_df_test = pd.DataFrame(word_matrix_test.toarray(), columns=vectorizer.get_feature_names_out())

    # Set the appropriate columns in df_test based on the presence in 'message'
    for col in word_df_test.columns:
        if col in df_test.columns:
            df_test[col] = word_df_test[col]

    return df, df_test

# Apply the function
df, df_test = add_missing_columns(df, df_test)

# Show the updated DataFrames
print("Updated df columns:", df.columns)
print("Updated df_test columns:", df_test.columns)


<ipython-input-10-69cf4be02f67>:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_test[col] = 0  # Initialize with 0
<ipython-input-10-69cf4be02f67>:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_test[col] = 0  # Initialize with 0
<ipython-input-10-69cf4be02f67>:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newfra

Updated df columns: Index(['message', 'fingers', 'tail', 'species', 'acon', 'aeon', 'aeop', 'aeqn',
       'afgstix', 'airenix',
       ...
       'cybnon', 'faejix', 'rflikum', 'jynapz', 'wviana', 'ragix', 'hopiui',
       'iephyr', 'loeix', 'joyzol'],
      dtype='object', length=938)
Updated df_test columns: Index(['message', 'fingers', 'tail', 'aeiana', 'aeno', 'aeon', 'alezom',
       'algocix', 'algorik', 'algorix',
       ...
       'folwar', 'nanocom', 'nimbub', 'gryohox', 'krmkos', 'angstic',
       'celwstar', 'lazervn', 'kkmeta', 'akiana'],
      dtype='object', length=937)


In [13]:
df.drop('message', axis=1, inplace=True)
df_test.drop('message', axis=1, inplace=True)

In [14]:
df_test.head()

fingers  tail  aeiana  aeno  aeon  alezom  algocix  algorik  algorix  \
0        2     0       0     0     0       0        0        0        0   
1        4     1       0     0     0       0        0        0        0   
2        4     1       0     0     0       0        0        0        0   
3        3     0       0     0     0       0        0        0        0   
4        4     1       0     0     0       0        0        0        0   

   angstix  ...  folwar  nanocom  nimbub  gryohox  krmkos  angstic  celwstar  \
0        0  ...       0        0       0        0       0        0         0   
1        0  ...       0        0       0        0       0        0         0   
2        0  ...       0        0       0        0       0        0         0   
3        0  ...       0        0       0        0       0        0         0   
4        0  ...       0        0       0        0       0        0         0   

   lazervn  kkmeta  akiana  
0        0       0       0  
1        0       0       0  
2        0       0       0  
3        0       0       0  
4        0       0       0  

[5 rows x 936 columns]

In [15]:
df.head()

fingers  tail  species  acon  aeon  aeop  aeqn  afgstix  airenix  akiana  \
0        4     0   Aquari     0     0     0     0        0        0       0   
1        5     1  Zorblax     0     0     0     0        0        0       0   
2        5     1  Zorblax     0     0     0     0        0        0       0   
3        2     1  Florian     0     0     0     0        0        0       0   
4        4     0   Faerix     0     0     0     0        0        0       0   

   ...  cybnon  faejix  rflikum  jynapz  wviana  ragix  hopiui  iephyr  loeix  \
0  ...       0       0        0       0       0      0       0       0      0   
1  ...       0       0        0       0       0      0       0       0      0   
2  ...       0       0        0       0       0      0       0       0      0   
3  ...       0       0        0       0       0      0       0       0      0   
4  ...       0       0        0       0       0      0       0       0      0   

   joyzol  
0       0  
1       0  
2       0  
3       0  
4       0  

[5 rows x 937 columns]

In [16]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix



# Separating features (X) by dropping the 'species' column
X = df.drop(columns=['species'])

# Target column (y) remains the 'species' column
y = df['species']

# Label encode the target variable 'species'
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

# Split the dataset into training and test sets (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.2, random_state=42)

# Initialize the K-Nearest Neighbors classifier
knn = KNeighborsClassifier(n_neighbors=1)  # k=3 as an example

# Train the KNN model
knn.fit(X_train, y_train)

# Make predictions on the test data
y_test_pred = knn.predict(X_test)

# Generate and print classification report
print("Classification Report:")
print(classification_report(y_test, y_test_pred, target_names=label_encoder.classes_))

# Generate and print confusion matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_test_pred))

# Analyze the results to identify and handle any low-performing classes
print("\nAnalysis of Low-Performing Classes:")
class_report = classification_report(y_test, y_test_pred, output_dict=True)

# Create a list of low-performing classes based on F1-score
low_performing_classes = {label: metrics for label, metrics in class_report.items()
                          if label != 'accuracy' and metrics['f1-score'] < 0.7}

print("Classes with F1-score < 0.6:")
for cls, metrics in low_performing_classes.items():
    print(f"{cls}: Precision = {metrics['precision']:.2f}, Recall = {metrics['recall']:.2f}, F1-score = {metrics['f1-score']:.2f}")

Classification Report:
              precision    recall  f1-score   support

      Aquari       0.60      0.75      0.67         4
       Cybex       0.92      1.00      0.96        12
    Emotivor       0.78      0.88      0.82         8
      Faerix       0.77      0.71      0.74        14
     Florian       0.86      0.67      0.75         9
     Mythron       0.78      0.70      0.74        10
      Nexoon       0.50      0.71      0.59         7
     Quixnar       0.72      0.93      0.81        14
     Sentire       0.80      0.44      0.57         9
     Zorblax       0.82      0.69      0.75        13

    accuracy                           0.76       100
   macro avg       0.75      0.75      0.74       100
weighted avg       0.77      0.76      0.76       100

Confusion Matrix:
[[ 3  0  0  0  1  0  0  0  0  0]
 [ 0 12  0  0  0  0  0  0  0  0]
 [ 0  0  7  0  0  0  0  0  1  0]
 [ 0  0  0 10  0  2  1  1  0  0]
 [ 2  0  0  0  6  0  1  0  0  0]
 [ 0  0  0  3  0  7  0  0  0  0]
 [

In [13]:
# cv_scores = cross_val_score(knn, X, y_encoded, cv=5)  # 5-fold cross-validation

# # Print cross-validation scores
# print("Cross-Validation Scores:", cv_scores)

In [14]:
# import pandas as pd
# from sklearn.model_selection import cross_val_score
# from sklearn.preprocessing import LabelEncoder
# from sklearn.neighbors import KNeighborsClassifier
# import numpy as np

# # Range of k values to test
# k_values = range(1, 21)
# mean_scores = []

# # Evaluate KNN for each k value
# for k in k_values:
#     knn = KNeighborsClassifier(n_neighbors=k)
#     cv_scores = cross_val_score(knn, X, y_encoded, cv=5)
#     mean_scores.append(cv_scores.mean())

# # Find the best k value
# best_k = k_values[np.argmax(mean_scores)]
# best_score = max(mean_scores)

# # Print results
# print("Mean Cross-Validation Scores:", mean_scores)
# print(f"Best k: {best_k} with a score of: {best_score:.2f}")

In [19]:
# Get the order of columns from X_train
column_order = X_train.columns.tolist()

# Reorder df and df_test to match the order of X_train
df = df[column_order]
df_test = df_test[column_order]

# Ensure 'message', 'tail', and 'fingers' columns remain unchanged
for col in ['message', 'tail', 'fingers']:
    if col in df.columns:
        df[col] = df[col]
    if col in df_test.columns:
        df_test[col] = df_test[col]


print("Reordered df_test columns:", df_test.columns.tolist())


Reordered df_test columns: ['fingers', 'tail', 'acon', 'aeon', 'aeop', 'aeqn', 'afgstix', 'airenix', 'akiana', 'akon', 'algorid', 'algorix', 'aneius', 'angsqix', 'angstic', 'angstix', 'angstox', 'angxtix', 'annstix', 'anxids', 'anxims', 'anxius', 'anxiuz', 'anzius', 'aoblax', 'aqjos', 'aqpos', 'aquoe', 'aquon', 'aquos', 'arbon', 'arbor', 'arbsr', 'arcor', 'ariana', 'asbron', 'aslron', 'astrln', 'astrob', 'astroh', 'astron', 'astrrn', 'avcana', 'aviaia', 'aviana', 'avisna', 'aviyna', 'awezom', 'awezon', 'awezox', 'awozom', 'bdissam', 'beadtix', 'beastij', 'beastit', 'beastix', 'beastpx', 'beasxix', 'beepod', 'bgissam', 'biokex', 'biomar', 'biompr', 'biomvr', 'biorex', 'biotex', 'bitanos', 'biumar', 'blaloz', 'blapnz', 'blapoz', 'blastix', 'blatoz', 'blessam', 'bliisam', 'bliskam', 'blisqam', 'blissac', 'blissam', 'blissxm', 'blnssam', 'boyzor', 'bqapoz', 'bvapoz', 'cacmox', 'calmoa', 'calmox', 'cbbron', 'ceaestar', 'cebrex', 'cehestar', 'celejtar', 'celestar', 'celistar', 'celwstar', 'c

In [20]:
X_new = df_test  # Assuming df_test also has the 'species' column
# Ensure that df_test does not have a 'species' column for predictions

# Make predictions on the new test set
y_new_pred = knn.predict(X_new)

# If you want to get the predicted classes in original labels
y_new_pred_labels = label_encoder.inverse_transform(y_new_pred)

# Create a DataFrame to display predictions
predictions_df = pd.DataFrame({'Predicted Species': y_new_pred_labels})

predictions_df.head()

Predicted Species
0            Aquari
1           Sentire
2           Florian
3           Mythron
4            Nexoon

In [21]:
# Assuming y_new_pred_labels is already created
df_test['Predicted Species'] = y_new_pred_labels

# Display the updated df_test with predictions
print(df_test.head())


   fingers  tail  acon  aeon  aeop  aeqn  afgstix  airenix  akiana  akon  ...  \
0        2     0     0     0     0     0        0        0       0     0  ...   
1        4     1     0     0     0     0        0        0       0     0  ...   
2        4     1     0     0     0     0        0        0       0     0  ...   
3        3     0     0     0     0     0        0        0       0     0  ...   
4        4     1     0     0     0     0        0        0       0     0  ...   

   faejix  rflikum  jynapz  wviana  ragix  hopiui  iephyr  loeix  joyzol  \
0       0        0       0       0      0       0       1      0       0   
1       0        0       0       0      0       0       0      0       0   
2       0        0       0       0      0       0       0      0       0   
3       0        0       0       0      0       0       0      0       0   
4       0        0       0       0      0       0       0      0       0   

   Predicted Species  
0             Aquari  
1         

<ipython-input-21-7d69aa043ea8>:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_test['Predicted Species'] = y_new_pred_labels


In [22]:
df_test.pd_to_csv('testout.csv', index=False)

AttributeError: 'DataFrame' object has no attribute 'pd_to_csv'

In [23]:
testout=pd.read_csv('/content/drive/MyDrive/INNOV8-2.0-47055a37a3bccfe6a5b7de82a2e87f9bc71a24bc/INNOV8-2.0-47055a37a3bccfe6a5b7de82a2e87f9bc71a24bc/test.csv')

In [25]:
testout.shape

(299, 3)

In [26]:
predictions_df.reset_index(drop=True, inplace=True)
testout.reset_index(drop=True, inplace=True)

# Left join predictions_df with testout
merged_df = testout.merge(predictions_df, left_index=True, right_index=True, how='left')

# Save the merged DataFrame to a new CSV file
merged_df.to_csv('merged_testout.csv', index=False)

In [27]:
merged_df.head()

message  fingers tail  \
0         iephyr terram nimbus terram faunar foliar        2   no   
1        joyzor uleex luvium caloox shockus blissae        4  yes   
2                                aquos arbor ventuc        4  yes   
3  nympha nympha epikoz nympha mythox mythox mythox        3   no   
4                            diitax sibenix fabulon        4  yes   

  Predicted Species  
0            Aquari  
1           Sentire  
2           Florian  
3           Mythron  
4            Nexoon